# Dual 2 to-4-Line Decoder DIP definition
# https://github.com/tgtakaoka/dip
name = "74139"
title = "CD74HCT139E"
dip = 16
width = 300
1 = "#1E"
2 = "1A0"
3 = "1A1"
4 = "#1Y0"
5 = "#1Y1"
6 = "#1Y2"
7 = "#1Y3"
8 = "GND"
9 = "#2Y3"
10 = "#2Y2"
11 = "#2Y1"
12 = "#2Y0"
13 = "2A1"
14 = "2A0"
15 = "#2W"
16 = "Vcc"
