# Quad D-Type Flip-Flop DIP definition
# https://github.com/tgtakaoka/dip
name = "74173"
title = "CD74HCT173E"
dip = 16
width = 300
1 = "#OE1"
2 = "#OE2"
3 = "Q0"
4 = "Q1"
5 = "Q2"
6 = "Q3"
7 = "CP"
8 = "GND"
9 = "#E1"
10 = "#E2"
11 = "D3"
12 = "D2"
13 = "D1"
14 = "D0"
15 = "MR"
16 = "Vcc"
