# Octal D-Type Latches DIP definition
# https://github.com/tgtakaoka/dip
name = "74573"
title = "CD74HCT573E"
dip = 20
width = 300
1 = "#OE"
2 = "1D"
3 = "2D"
4 = "3D"
5 = "4D"
6 = "5D"
7 = "6D"
8 = "7D"
9 = "8D"
10 = "GND"
11 = "LE"
12 = "8Q"
13 = "7Q"
14 = "6Q"
15 = "5Q"
16 = "4Q"
17 = "3Q"
18 = "2Q"
19 = "1Q"
20 = "Vcc"
