# Octal Comparator DIP definition
# https://github.com/tgtakaoka/dip
name = "74688"
title = "CD74HCT688E"
dip = 20
width = 300
1 = "#E"
2 = "A0"
3 = "B0"
4 = "A1"
5 = "B1"
6 = "A2"
7 = "B2"
8 = "A3"
9 = "B3"
10 = "GND"
11 = "A4"
12 = "B4"
13 = "A5"
14 = "B5"
15 = "A6"
16 = "B6"
17 = "A7"
18 = "B7"
19 = "#Y"
20 = "Vcc"
