# IM6100 DIP definition
# https://github.com/tgtakaoka/dip
name = "IM6100"
title = "IM6100"
dip = 40
width = 600
 1 = "VCC"
 2 = "RUN"
 3 = "DMAGNT"
 4 = "#DMAREQ"
 5 = "#CPREQ"
 6 = "#RUN/HLT"
 7 = "#RESET"
 8 = "#INTREQ"
 9 = "XTA"
10 = "LXMAR"
11 = "#WAIT"
12 = "XTB"
13 = "XTC"
14 = "OSC OUT"
15 = "OSC IN"
16 = "DX0"
17 = "DX1"
18 = "DX2"
19 = "DX3"
20 = "DX4"
21 = "DX5"
22 = "DX6"
23 = "DX7"
24 = "DX8"
25 = "DX9"
26 = "GND"
27 = "DX10"
28 = "DX11"
29 = "LINK"
30 = "#DEVSEL"
31 = "#SWSEL"
32 = "#C0"
33 = "#C1"
34 = "#C2"
35 = "#SKP"
36 = "IFETCH"
37 = "#MEMSEL"
38 = "#CPSEL"
39 = "INTGNT"
40 = "DATAF"
