# MN1613 DIP definition
# https://github.com/tgtakaoka/dip
name = "MN1613"
dip = 40
width = 600
 1 = "#OE"
 2 = "EA0, FSYNC"
 3 = "EA1, CSTP"
 4 = "BS00"
 5 = "BS01"
 6 = "BS02"
 7 = "BS03"
 8 = "BS04"
 9 = "BS05"
10 = "BS06"
11 = "BS07"
12 = "BS08"
13 = "BS09"
14 = "BS10"
15 = "BS11"
16 = "BS12"
17 = "BS13"
18 = "BS14"
19 = "BS15"
20 = "VSS"
21 = "#ST"
22 = "#SD"
23 = "#CSRQ, #RUN"
24 = "#STRT"
25 = "#HLT"
26 = "#IRQ0"
27 = "#IRQ1"
28 = "#IRQ2"
29 = "#RST"
30 = "BSAV"
31 = "#DTAK"
32 = "#BSRQ"
33 = "IOP"
34 = "WRT"
35 = "#DTSD"
36 = "ADSD"
37 = "SYNC"
38 = "X2"
39 = "X1"
40 = "VDD"
