# MN1613A DIP definition
# https://github.com/tgtakaoka/dip
name = "MN1613A"
dip = 42
width = 600
 1 = "EA1"
 2 = "#OE"
 3 = "EA2, FSYNC"
 4 = "EA3, CSTP"
 5 = "BS00"
 6 = "BS01"
 7 = "BS02"
 8 = "BS03"
 9 = "BS04"
10 = "BS05"
11 = "BS06"
12 = "BS07"
13 = "BS08"
14 = "BS09"
15 = "BS10"
16 = "BS11"
17 = "BS12"
18 = "BS13"
19 = "BS14"
20 = "BS15"
21 = "VSS"
22 = "#ST"
23 = "#SD"
24 = "#CSRQ, #RUN"
25 = "#STRT"
26 = "#HLT"
27 = "#IRQ0"
28 = "#IRQ1"
29 = "#IRQ2"
30 = "#RST"
31 = "BSAV"
32 = "#DTAK"
33 = "#BSRQ"
34 = "IOP"
35 = "WRT"
36 = "#DTSD"
37 = "ADSD"
38 = "SYNC"
39 = "X2"
40 = "X1"
41 = "VDD"
42 = "EA0"
