# MSM80C39RS DIP definition
# https://github.com/tgtakaoka/dip
name = "80C39"
title = "MSM80C32RS"
dip = 40
width = 600
1 = "T0"
2 = "XTAL1"
3 = "XTAL2"
4 = "#RESET"
5 = "#SS"
6 = "#INT"
7 = "EA"
8 = "#RD"
9 = "#PSEN"
10 = "#WR"
11 = "ALE"
12 = "DB0"
13 = "DB1"
14 = "DB2"
15 = "DB3"
16 = "DB4"
17 = "DB5"
18 = "DB6"
19 = "DB7"
20 = "VSS"
21 = "A8"
22 = "A9"
23 = "A10"
24 = "A11"
25 = "#PROG"
26 = "VDD"
27 = "P10"
28 = "P11"
29 = "P12"
30 = "P13"
31 = "P14"
32 = "P15"
33 = "P16"
34 = "P17"
35 = "P24"
36 = "P25"
37 = "P26"
38 = "P27"
39 = "T1"
40 = "VCC"

