# P8095BH DIP definition
# https://github.com/tgtakaoka/dip
name = "P8095BH"
title = "P8095BH"
dip = 48
width = 600
 1 = "RXD,   P2.1"
 2 = "TXD,   P2.0"
 3 = "HSI.0,      , SID.0"
 4 = "HSI.1,      , SID.1"
 5 = "HSI.2, HSO.4, SID.2"
 6 = "HSI.3, HSO.5, SID.3"
 7 = "HSO.0"
 8 = "HSO.1"
 9 = "HSO.2"
10 = "HSO.3"
11 = "Vss"
12 = "Vpp"
13 = "PWM,   P2.5"
14 = "#WR,   #WRL"
15 = "#HBE,  #WRH"
16 = "READY"
17 = "AD15.  P4.7"
18 = "AD14,  P4.6"
19 = "AD13,  P4.5"
20 = "AD12,  P4.4"
21 = "AD11,  P4.3"
22 = "AD10,  P4.2"
23 = "AD9,   P4.1"
24 = "AD8,   P4.0"
25 = "AD7,   P3.7"
26 = "AD6,   P3.6"
27 = "AD5,   P3.5"
28 = "AD4,   P3.4"
29 = "AD3,   P3.3"
30 = "AD2,   P3.2"
31 = "AD1,   P3.1"
32 = "AD0,   P3.0"
33 = "#RD"
34 = "ALE,   #ADV"
35 = "XTAL2"
36 = "XTAL1"
37 = "Vss"
38 = "Vcc"
39 = "#EA"
40 = "ACH6,  P0.6"
41 = "ACH7,  P0.7"
42 = "ACH5,  P0.5"
43 = "ACH4,  P0.4"
44 = "ANGND"
45 = "Vref"
46 = "Vpd"
47 = "EXTINT, P2.2"
48 = "#RESET"
