# P80C32 DIP definition
# https://github.com/tgtakaoka/dip
name = "P80C32"
title = "P80C32/P80C51"
dip = 40
width = 600
1 = "P1.0"
2 = "P1.1"
3 = "P1.2"
4 = "P1.3"
5 = "P1.4"
6 = "P1.5"
7 = "P1.6"
8 = "P1.7"
9 = "RST"
10 = "P3.0, RxD"
11 = "P3.1, TxD"
12 = "P3.2, #INT0"
13 = "P3.3, #INT1"
14 = "P3.4"
15 = "P3.5"
16 = "#WR"
17 = "#RD"
18 = "XTAL2"
19 = "XTAL1"
20 = "VSS"
21 = "A8"
22 = "A9"
23 = "A10"
24 = "A11"
25 = "A12"
26 = "A13"
27 = "A14"
28 = "A15"
29 = "#PSEN"
30 = "ALE"
31 = "#EA"
32 = "AD7"
33 = "AD6"
34 = "AD5"
35 = "AD4"
36 = "AD3"
37 = "AD2"
38 = "AD1"
39 = "AD0"
40 = "VCC"
