# Teensy 3.5 DIP definition
# https://github.com/tgtakaoka/dip
name = "Teensy 3.5"
title = "Teensy 3.5/MK64FX512VND12"
dip = 48
width = 600
1 = "GND"
2 = "PTB16, D0, RXD1"
3 = "PTB17, D1, TXD1"
4 = "PTD0,  D2, FTM3_CH0"
5 = "PTA12, D3, FTM1_CH0"
6 = "PTA13, D4, FTM1_CH1"
7 = "PTD7,  D5, FTM0_CH7"
8 = "PTD4,  D6, FTM0_CH4"
9 = "PTD2,  D7, FTM3_CH2"
10 = "PTD3,  D8, FTM3_CH3"
11 = "PTC3,  D9, FTM0_CH2"
12 = "PTC4, D10, FTM0_CH3"
13 = "PTC6, D11"
14 = "PTC7, D12"
15 = "3.3V"
16 = "PTE26, D24"
17 = "PTA5,  D25"
18 = "PTA14, D26"
19 = "PTA15, D27"
20 = "PTA16, D28"
21 = "PTB18, D29, FTM2_CH0"
22 = "PTB19, D30, FTM2_CH1"
23 = "PTB10, D31, RXD4"
24 = "PTB11, D32, TXD4"
25 = "PTE24, D33, RXD5"
26 = "PTE25, D34, TXD5"
27 = "PTC8,  D35, FTM3_CH4"
28 = "PTC9,  D36, FTM3_CH5"
29 = "PTC10, D37, FTM3_CH6"
30 = "PTC11, D38, FTM3_CH7"
31 = "PTA17, D39, A20"
32 = "     ,    , A21"
33 = "     ,    , A22"
34 = "GND"
35 = "PTC5,  D13, LED"
36 = "PTD1,  D14, FTM3_CH1"
37 = "PTC0,  D15, A1"
38 = "PTB0,  D16, A2"
39 = "PTB1,  D17, A3"
40 = "PTB3,  D18, A4"
41 = "PTB2,  D19, D5"
42 = "PTD5,  D20, FTM0_CH5"
43 = "PTD6,  D21, FTM0_CH6"
44 = "PTC1,  D22, FTM0_CH0"
45 = "PTC2,  D23, FTM0_CH1"
46 = "3.3V"
47 = "AGND"
48 = "VIN"
