# Z88C00 DIP definition
# https://github.com/tgtakaoka/dip
name = "Z88C00"
title = "Z88C00 (Super8)"
dip = 48
width = 600
 1 = "AD0"
 2 = "AD1"
 3 = "AD2"
 4 = "AD3"
 5 = "AD4"
 6 = "AD5"
 7 = "AD6"
 8 = "AD7"
 9 = "P24, #IRQ4"
10 = "P25, #IRQ4"
11 = "VCC"
12 = "XTAL2"
13 = "XTAL1"
14 = "P44"
15 = "P45"
16 = "P46"
17 = "P47"
18 = "P22"
19 = "P32"
20 = "P33, #IRQ0"
21 = "P23, #IRQ0"
22 = "P20, #IRQ6"
23 = "P21, #IRQ1"
24 = "P31, TxD, #IRQ1"
25 = "P30, RxD, #IRQ6"
26 = "P26, #IRQ2"
27 = "P27, #IRQ2"
28 = "P37, #IRQ5"
29 = "P36, #IRQ5"
30 = "#RESET"
31 = "R/W"
32 = "P43"
33 = "P42"
34 = "GND"
35 = "P41"
36 = "P40"
37 = "#DS"
38 = "#AS"
39 = "P35, #DM,   #IRQ7"
40 = "P34, #WAIT, #IRQ7"
41 = "A15"
42 = "A14"
43 = "A13"
44 = "A12"
45 = "A11"
46 = "A10"
47 = "A9"
48 = "A8"
