# ATmega1284P DIP definition
# https://github.com/tgtakaoka/dip
name = "ATmega1284P"
title = "ATmega1284P/MightyCore"
dip = 40
width = 600
1 = "PB0, D0, LED"
2 = "PB1, D1"
3 = "PB2, D2, INT2"
4 = "PB3, D3"
5 = "PB4, D4, SS"
6 = "PB5, D5, MOSI"
7 = "PB6, D6, MISO"
8 = "PB7, D7, SCK"
9 = "#RESET"
10 = "VCC"
11 = "GND"
12 = "XTAL2"
13 = "XTAL1"
14 = "PD0, D8, RXD"
15 = "PD1, D9, TXD"
16 = "PD2, D10, INT0"
17 = "PD3, D11, INT1"
18 = "PD4, D12, OC1B"
19 = "PD5, D13, OC1A"
20 = "PD6, D14, OC2B"
21 = "PD7, D15, OC2A"
22 = "PC0, D16, SCL"
23 = "PC1, D17, SDA"
24 = "PC2, D18"
25 = "PC3, D19"
26 = "PC4, D20"
27 = "PC5, D21"
28 = "PC6, D22"
29 = "PC7, D23"
30 = "AVCC"
31 = "GND"
32 = "AREF"
33 = "PA7, D31, ADC7"
34 = "PA6, D30, ADC6"
35 = "PA5, D29, ADC5"
36 = "PA4, D28, ADC4"
37 = "PA3, D27, ADC3"
38 = "PA2, D26, ADC2"
39 = "PA1, D25, ADC1"
40 = "PA0, D24, ADC0"
