# ATmega4809P DIP definition
# https://github.com/tgtakaoka/dip
name = "ATmega4809P"
title = "ATmega4809P/MegaCoreX"
dip = 40
width = 600
1 = "PC0, D14, TXD1, 1IN0"
2 = "PC1, D15, RXD1, 1IN1"
3 = "PC2, D15,     , 1IN2"
4 = "PC3, D17,     , 1OUT"
5 = "VDD"
6 = "GND"
7 = "PC4, D18"
8 = "PC5, D19"
9 = "PD0, D22, A0, 2IN0"
10 = "PD1, D23, A1, 2IN1"
11 = "PD2, D24, A2, 2IN2"
12 = "PD3, D25, A3, 2OUT"
13 = "PD4, D26, A4"
14 = "PD5, D27, A5"
15 = "PD6, D28, A6, 2OUT'"
16 = "PD7, D29, A7"
17 = "AVDD"
18 = "GND"
19 = "PE0, D30, A8"
20 = "PE1, D31, A9"
21 = "PE2, D32, A10"
22 = "PE3, D33, A11"
23 = "PF0, D34, TXD2, 3IN0"
24 = "PF1, D35, RXD2, 3IN1"
25 = "PF2, D36, A12, 3IN2"
26 = "PF3, D37, A13, 3OUT"
27 = "PF4, D38, A14"
28 = "PF5, D39, A15, LED"
29 = "PF6, D40, #RESET, 3OUT'"
30 = "UPDI"
31 = "VDD"
32 = "GND"
33 = "PA0, D0, TXD0, 0IN0"
34 = "PA1, D1, RXD0, 0IN1"
35 = "PA2, D2, SDA, 0IN2"
36 = "PA3, D3, SCL, 0OUT"
37 = "PA4, D4, MOSI"
38 = "PA5, D5, MISO"
39 = "PA6, D6, SCK, 0OUT'"
40 = "PA7, D7, SS"
