# ATmega328P DIP definition
# https://github.com/tgtakaoka/dip
name = "ATmega328P"
title = "ATmega328P/MiniCore"
dip = 28
width = 300
1 = "PC6, D22, #RESET"
2 = "PD0, D0, RXD"
3 = "PD1, D1, TXD"
4 = "PD2, D2, INT0"
5 = "PD3, D3, INT1"
6 = "PD4, D4"
7 = "VCC"
8 = "GND"
9 = "PB6, D20, XTAL1"
10 = "PB7, D21, XTAL2"
11 = "PD5, D5, OC0B"
12 = "PD6, D6, OC0A"
13 = "PD7, D7"
14 = "PB0, D8"
15 = "PB1, D9,    , OC1A"
16 = "PB2, D10, SS, OC1B"
17 = "PB3, D11, MOSI, OC2A"
18 = "PB4, D12, MISO"
19 = "PB5, D13, SCK"
20 = "AVCC"
21 = "AREF"
22 = "GND"
23 = "PC0, D14, ADC0"
24 = "PC1, D15, ADC1"
25 = "PC2, D16, ADC2"
26 = "PC3, D17, ADC3"
27 = "PC4, D18, ADC4, SDA"
28 = "PC5, D19, ADC5, SCL"
