# https://github.com/tgtakaoka/dip
name = "412"
title = "ATtiny412SS/megaTinyCore"
dip = 8
width = 300
1 = "VDD"
2 = "PA6, D0"
3 = "PA7, D1"
4 = "PA1, D2"
5 = "PA2, D3"
6 = "PA0, D5, UPDI"
7 = "PA3, D4"
8 = "GND"
