# https://github.com/tgtakaoka/dip
name = "tiny3216"
title = "ATtiny3216SS/megaTinyCore"
dip = 20
width = 300
1 = "VCC"
2 = "PA4, D0"
3 = "PA5, D1"
4 = "PA6, D2"
5 = "PA7, D3"
6 = "PB5, D4"
7 = "PB4, D5"
8 = "PB3, D6, RXD"
9 = "PB2, D7, TXD"
10 = "PB1, D8"
11 = "PB0, D9"
12 = "PC0, D10"
13 = "PC1, D11"
14 = "PC2, D12"
15 = "PC3, D13"
16 = "UPDI, D17"
17 = "PA1, D14, MOSI"
18 = "PA2, D15, MISO"
19 = "PA3, D16, SCK"
20 = "GND"
