# Octal 3-State Buffer DIP definition
# https://github.com/tgtakaoka/dip
name = "74541"
title = "CD74HCT541E"
dip = 20
width = 300
1 = "#OE1"
2 = "A0"
3 = "A1"
4 = "A2"
5 = "A3"
6 = "A4"
7 = "A5"
8 = "A6"
9 = "A7"
10 = "GND"
11 = "Y7"
12 = "Y6"
13 = "Y5"
14 = "Y4"
15 = "Y3"
16 = "Y2"
17 = "Y1"
18 = "Y0"
19 = "#OE2"
20 = "Vcc"
