# 4-ch Tristate Buffers DIP definition
# https://github.com/tgtakaoka/dip
name = "74126"
title = "CD74HCT126E"
dip = 14
width = 300
1 = "1OE"
2 = "1A"
3 = "1Y"
4 = "2OE"
5 = "2A"
6 = "2Y"
7 = "GND"
8 = "3Y"
9 = "3A"
10 = "3OE"
11 = "4Y"
12 = "4A"
13 = "4OE"
14 = "Vcc"
