# F3850 DIP definition
# https://github.com/tgtakaoka/dip
name = "F3850"
title = "F3850"
dip = 40
width = 600
 1 = "PHI"
 2 = "WRITE"
 3 = "VDD"
 4 = "VGG"
 5 = "#IO03"
 6 = "DB3"
 7 = "#IO13"
 8 = "#IO12"
 9 = "DB2"
10 = "#IO02"
11 = "#IO01"
12 = "DB1"
13 = "#IO11"
14 = "#IO10"
15 = "DB0"
16 = "#IO00"
17 = "ROMC0"
18 = "ROMC1"
19 = "ROMC2"
20 = "ROMC3"
21 = "ROMC4"
22 = "#ICB"
23 = "#INTREQ"
24 = "VSS"
25 = "#IO07"
26 = "DB7"
27 = "#IO17"
28 = "#IO16"
29 = "DB6"
30 = "#IO06"
31 = "#IO05"
32 = "DB5"
33 = "#IO15"
34 = "#IO14"
35 = "DB4"
36 = "#IO04"
37 = "#EXTRES"
38 = "XTLY"
39 = "XTLX"
40 = "XTLZ"
