# Octal Level Shifter
# https://github.com/tgtakaoka/dip
name = "FXMA108"
title = "FXMA108"
dip = 20
width = 300
1 = "VccA"
2 = "A0"
3 = "A1"
4 = "A2"
5 = "A3"
6 = "A4"
7 = "A5"
8 = "A6"
9 = "A7"
10 = "GND"
11 = "#OE"
12 = "B7"
13 = "B6"
14 = "B5"
15 = "B4"
16 = "B3"
17 = "B2"
18 = "B1"
19 = "B0"
20 = "VccB"
