# HD-6120 DIP definition
# https://github.com/tgtakaoka/dip
name = "HD-6120"
title = "HD-6120"
dip = 40
width = 600
 1 = "@OUT"
 2 = "DMAGNT"
 3 = "#DMAREQ"
 4 = "#SKP"
 5 = "RUN/#HLT"
 6 = "#RUN"
 7 = "#RESET"
 8 = "ACK"
 9 = "OSCIN"
10 = "OSCOUT"
11 = "#IFETCH"
12 = "DX0"
13 = "DX1"
14 = "DX2"
15 = "DX3"
16 = "DX4"
17 = "DX5"
18 = "DX6"
19 = "DX7"
20 = "VSS"
21 = "DX8"
22 = "DX9"
23 = "DX10"
24 = "DX11"
25 = "EMA0/#C0"
26 = "EMA1/#C1"
27 = "EMA2"
28 = "STRTUP"
29 = "#CPREQ"
30 = "#INTREEQ"
31 = "#INTGNT"
32 = "#DATAF"
33 = "#LXPAR"
34 = "#LXMAR"
35 = "#LXDAR"
36 = "#IOCLR"
37 = "#MEMSEL"
38 = "#WRITE"
39 = "#READ"
40 = "VCC"
