# HD6301V1P DIP definition
# https://github.com/tgtakaoka/dip
name = "HD6301V1P"
title = "HD6301V1P Mode1"
dip = 40
width = 600
1 = "VSS"
2 = "XTAL"
3 = "EXTAL"
4 = "#NMI"
5 = "#IRQ1"
6 = "#RESET"
7 = "#STBY"
8 = "P20, PC0"
9 = "P21, PC1"
10 = "P22, PC2"
11 = "P23, RXD"
12 = "P24, TXD"
13 = "A0"
14 = "A1"
15 = "A2"
16 = "A3"
17 = "A4"
18 = "A5"
19 = "A6"
20 = "A7"
21 = "VCC"
22 = "A15"
23 = "A14"
24 = "A13"
25 = "A12"
26 = "A11"
27 = "A10"
28 = "A9"
29 = "A8"
30 = "D7"
31 = "D6"
32 = "D5"
33 = "D4"
34 = "D3"
35 = "D2"
36 = "D1"
37 = "D0"
38 = "R/W"
39 = "NC"
40 = "E"
