# HM628128 DIP definition
# https://github.com/tgtakaoka/dip
name = "HM62812DLP"
dip = 32
width = 600
1 = "NC"
2 = "A16"
3 = "A14"
4 = "A12"
5 = "A7"
6 = "A6"
7 = "A5"
8 = "A4"
9 = "A3"
10 = "A2"
11 = "A1"
12 = "A0"
13 = "D0"
14 = "D1"
15 = "D2"
16 = "VSS"
17 = "D3"
18 = "D4"
19 = "D5"
20 = "D6"
21 = "D7"
22 = "#CS1"
23 = "A10"
24 = "#OE"
25 = "A11"
26 = "A9"
27 = "A8"
28 = "A13"
29 = "#WE"
30 = "CS2"
31 = "A15"
32 = "VCC"
