# INS8060 DIP definition
# https://github.com/tgtakaoka/dip
name = "INS8060"
title = "INS8060(SC/MP II)"
dip = 40
width = 600
1 = "#WDS"
2 = "#RDS"
3 = "#ENIN"
4 = "#ENOUT"
5 = "#BREQ"
6 = "#HOLD"
7 = "#RST"
8 = "CONT"
9 = "D0, A12"
10 = "D1, A13"
11 = "D2, A14"
12 = "D3, A15"
13 = "D4, R"
14 = "D5, I"
15 = "D6, D"
16 = "D7, H"
17 = "SENSA"
18 = "SENSB"
19 = "FLAG0"
20 = "GND"
21 = "FLAG1"
22 = "FLAG2"
23 = "SOUT"
24 = "SIN"
25 = "A0"
26 = "A1"
27 = "A2"
28 = "A3"
29 = "A4"
30 = "A5"
31 = "A6"
32 = "A7"
33 = "A8"
34 = "A9"
35 = "A10"
36 = "A11"
37 = "XIN"
38 = "XOUT"
39 = "#ADS"
40 = "VCC"
