# INS8070 DIP definition
# https://github.com/tgtakaoka/dip
name = "INS8070"
title = "INS8070(SC/MP III)"
dip = 40
width = 600
1 = "#ENOUT"
2 = "#ENIN"
3 = "#BREQ"
4 = "#RDS"
5 = "#HOLD"
6 = "#WDS"
7 = "XOUT"
8 = "XIN"
9 = "A15"
10 = "A14"
11 = "A13"
12 = "A12"
13 = "A11"
14 = "A10"
15 = "A9"
16 = "A8"
17 = "A7"
18 = "A6"
19 = "A5"
20 = "GND"
21 = "A4"
22 = "A3"
23 = "A2"
24 = "A1"
25 = "A0"
26 = "D7"
27 = "D6"
28 = "D5"
29 = "D4"
30 = "D3"
31 = "D2"
32 = "D1"
33 = "D0"
34 = "D1"
35 = "D20"
36 = "D31"
37 = "#RST"
38 = "SA"
39 = "SB"
40 = "VCC"
