# INS8060 DIP definition
# https://github.com/tgtakaoka/dip
name = "INS8060"
title = "INS8060(SC/MP II)"
dip = 40
width = 600
 1 = "#WDS"
 2 = "#RDS"
 3 = "#ENIN"
 4 = "#ENOUT"
 5 = "#BREQ"
 6 = "#HOLD"
 7 = "#RST"
 8 = "CONT"
 9 = "DB7, H"
10 = "DB6, D"
11 = "DB5, I"
12 = "DB4, R"
13 = "DB3, AD15"
14 = "DB2, AD14"
15 = "DB1, AD13"
16 = "DB0, AD12"
17 = "SENSA"
18 = "SENSB"
19 = "FLAG0"
20 = "GND"
21 = "FLAG1"
22 = "FLAG2"
23 = "SOUT"
24 = "SIN"
25 = "AD00"
26 = "AD01"
27 = "AD02"
28 = "AD03"
29 = "AD04"
30 = "AD05"
31 = "AD06"
32 = "AD07"
33 = "AD08"
34 = "AD09"
35 = "AD10"
36 = "AD11"
37 = "XIN"
38 = "XOUT"
39 = "#ADS"
40 = "VCC"
