# MC146805 DIP definition
# https://github.com/tgtakaoka/dip
name = "MC146805"
title = "MC6805/MC146805"
dip = 40
width = 600
1 = "#RESET"
2 = "#IRQ"
3 = "LI"
4 = "DS"
5 = "R/W"
6 = "AS"
7 = "PA7"
8 = "PA6"
9 = "PA5"
10 = "PA4"
11 = "PA3"
12 = "PA2"
13 = "PA1"
14 = "PA0"
15 = "A12"
16 = "A11"
17 = "A10"
18 = "A9"
19 = "A8"
20 = "VSS"
21 = "B7"
22 = "B6"
23 = "B5"
24 = "B4"
25 = "B3"
26 = "B2"
27 = "B1"
28 = "B0"
29 = "PB7"
30 = "PB6"
31 = "PB5"
32 = "PB4"
33 = "PB3"
34 = "PB2"
35 = "PB1"
36 = "PB0"
37 = "TIMER"
38 = "OSC2"
39 = "OSC1"
40 = "VDD"
