# MC68HC11A0 DIP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC11A0"
title = "MC68HC11A0 Mode3"
dip = 48
width = 600
1 = "PA7"
2 = "PA6"
3 = "PA5"
4 = "PA4"
5 = "PA3"
6 = "PA2"
7 = "PA1"
8 = "PA0"
9 = "A15"
10 = "A14"
11 = "A13"
12 = "A12"
13 = "A11"
14 = "A10"
15 = "A9"
16 = "A8"
17 = "PE0"
18 = "PE1"
19 = "PE2"
20 = "PE3"
21 = "VRL"
22 = "VRH"
23 = "VSS"
24 = "MODB, STBY"
25 = "MODA, #LIR"
26 = "AS"
27 = "E"
28 = "R/W"
29 = "EXTAL"
30 = "XTAL"
31 = "AD0"
32 = "AD1"
33 = "AD2"
34 = "AD3"
35 = "AD4"
36 = "AD5"
37 = "AD6"
38 = "AD7"
39 = "#RESET"
40 = "#XIRQ"
41 = "#IRQ"
42 = "PD0, RxD"
43 = "PD1, TxD"
44 = "PD2, MISO"
45 = "PD3, MOSI"
46 = "PD4, SCK"
47 = "PD5, #SS"
48 = "VDD"
