# MC6801 DIP definition
# https://github.com/tgtakaoka/dip
name = "MC6801"
title = "MC6801 Mode1"
dip = 40
width = 600
1 = "VSS"
2 = "XTAL"
3 = "EXTAL"
4 = "#NMI"
5 = "#IRQ1"
6 = "#RESET"
7 = "VCC"
8 = "P20, PC0"
9 = "P21, PC1"
10 = "P22, PC2"
11 = "P23, RXD"
12 = "P24, TXD"
13 = "P10"
14 = "P11"
15 = "P12"
16 = "P13"
17 = "P14"
18 = "P15"
19 = "P16"
20 = "P17"
21 = "VCC"
22 = "A7"
23 = "A6"
24 = "A5"
25 = "A4"
26 = "A3"
27 = "A2"
28 = "A1"
29 = "A0"
30 = "D7"
31 = "D6"
32 = "D5"
33 = "D4"
34 = "D3"
35 = "D2"
36 = "D1"
37 = "D0"
38 = "R/W"
39 = "#IOS"
40 = "E"
