# MC68008P DIP definition
# https://github.com/tgtakaoka/dip
name = "MC68008P"
dip = 48
width = 600
1 = "A3"
2 = "A4"
3 = "A5"
4 = "A6"
5 = "A7"
6 = "A8"
7 = "A9"
8 = "A10"
9 = "A11"
10 = "A12"
11 = "A13"
12 = "A14"
13 = "VCC"
14 = "A15"
15 = "GND"
16 = "A16"
17 = "A17"
18 = "A18"
19 = "A19"
20 = "D7"
21 = "D6"
22 = "D5"
23 = "D4"
24 = "D3"
25 = "D2"
26 = "D1"
27 = "D0"
28 = "#AS"
29 = "#DS"
30 = "R/W"
31 = "#DTACK"
32 = "#BG"
33 = "#BR"
34 = "CLK"
35 = "GND"
36 = "#HALT"
37 = "#RESET"
38 = "E"
39 = "#VPA"
40 = "#BERR"
41 = "#IPL1"
42 = "#IPL2/#IPL0"
43 = "FC2"
44 = "FC1"
45 = "FC0"
46 = "A0"
47 = "A1"
48 = "A2"
