# Arduino Nano Every DIP definition
# https://github.com/tgtakaoka/dip
name = "Nano Every"
title = "Arduino Nano Every"
dip = 30
width = 600
1 = "D13, PE2, SCK"
2 = "+3V3"
3 = "AREF, PD7"
4 = "D14/A0,  PD3, AIN3"
5 = "D15/A1,  PD2, AIN2"
6 = "D16/A2,  PD1, AIN1"
7 = "D17/A3,  PD0, AIN0"
8 = "D18/A4,  PA2, SDA"
9 = "D19/A5,  PA3, SCL"
10 = "D20/A6, PD4, AIN4"
11 = "D21/A7, PD5, AIN5"
12 = "+5V"
13 = "#RESET"
14 = "GND"
15 = "VIN"
16 = "TX, PC4,"
17 = "RX, PC5"
18 = "#RESET"
19 = "GND"
20 = "D2,   PA0"
21 = "D3~,  PF5"
22 = "D4,   PC6"
23 = "D5~,  PB2"
24 = "D6~,  PF4"
25 = "D7,   PA1"
26 = "D8,   PE3, SS"
27 = "D9~,  PB0"
28 = "D10~, PB1"
29 = "D11,  PE0, MOSI"
30 = "D12,  PE1, MISO"
