# Arduino Nano Every DIP definition
# https://github.com/tgtakaoka/dip
name = "Nano Every"
title = "Arduino Nano Every/MegaCoreX"
dip = 30
width = 600
1 = "D13, PE2"
2 = "3.3V"
3 = "D39, PD7"
4 = "D14, PD3"
5 = "D15, PD2"
6 = "D16, PD1"
7 = "D17, PD0"
8 = "D18, PA2, PF2"
9 = "D19, PA3, PF3"
10 = "D20, PD4"
11 = "D21, PD5"
12 = "5V"
13 = "#RST"
14 = "GND"
15 = "VIN"
16 = "D1, PC4"
17 = "D0, PC5"
18 = "#RST"
19 = "GND"
20 = "D2, PA0"
21 = "D3, PF5"
22 = "D4, PC6"
23 = "D5, PB2"
24 = "D6, PF4"
25 = "D7, PA1"
26 = "D8, PE3"
27 = "D9, PB0"
28 = "D10, PB1"
29 = "D11, PE0"
30 = "D12, PE1"
