# P8085AH DIP definition
# https://github.com/tgtakaoka/dip
name = "P8085AH"
dip = 40
width = 600
1 = "X1"
2 = "X2"
3 = "RESOUT"
4 = "SOD"
5 = "SID"
6 = "TRAP"
7 = "RST7.5"
8 = "RST6.5"
9 = "RST5.5"
10 = "INTR"
11 = "#INTA"
12 = "AD0"
13 = "AD1"
14 = "AD2"
15 = "AD3"
16 = "AD4"
17 = "AD5"
18 = "AD6"
19 = "AD7"
20 = "VSS"
21 = "A8"
22 = "A9"
23 = "A10"
24 = "A11"
25 = "A12"
26 = "A13"
27 = "A14"
28 = "A15"
29 = "S0"
30 = "ALE"
31 = "#WR"
32 = "#RD"
33 = "S1"
34 = "IO/M"
35 = "READY"
36 = "#RESIN"
37 = "CLKO"
38 = "HLDA"
39 = "HOLD"
40 = "VCC"
