# SCN2650A DIP definition
# https://github.com/tgtakaoka/dip
name = "SCN2650A"
dip = 40
width = 600
 1 = "SENSE"
 2 = "ADR12"
 3 = "ADR11"
 4 = "ADR10"
 5 = "ADR9"
 6 = "ADR8"
 7 = "ADR7"
 8 = "ADR6"
 9 = "ADR5"
10 = "ADR4"
11 = "ADR3"
12 = "ADR2"
13 = "ADR1"
14 = "ADR0"
15 = "#ADREN"
16 = "RESET"
17 = "#INTRQ"
18 = "ADR14, D/#C"
19 = "ADR13, E/#NE"
20 = "M/#IO"
21 = "GND"
22 = "WRP"
23 = "#R/W"
24 = "OPREQ"
25 = "#DBUSEN"
26 = "DBUS7"
27 = "DBUS6"
28 = "DBUS5"
29 = "DBUS4"
30 = "DBUS3"
31 = "DBUS2"
32 = "DBUS1"
33 = "DBUS0"
34 = "INTACK"
35 = "RUN/#WAIT"
36 = "#OPACK"
37 = "#PAUSE"
38 = "CLOCK"
39 = "VCC"
40 = "FLAG"
