# TMP90C802AP DIP definition
# https://github.com/tgtakaoka/dip
name = "TMP90C802AP"
title = "TMP90C802AP TLCS90"
dip = 40
width = 600
1 = "RxD"
2 = "#RTS"
3 = "TxD"
4 = "#RD"
5 = "#WR"
6 = "#WAIT"
7 = "INT0"
8 = "INT1"
9 = "#NMI"
10 = "#EA"
11 = "CLK"
12 = "D0"
13 = "D1"
14 = "D2"
15 = "D3"
16 = "D4"
17 = "D5"
18 = "D6"
19 = "D7"
20 = "GND"
21 = "X1"
22 = "X2"
23 = "#RESET"
24 = "A0"
25 = "A1"
26 = "A2"
27 = "A3"
28 = "A4"
29 = "A5"
30 = "A6"
31 = "A7"
32 = "A8"
33 = "A9"
34 = "A10"
35 = "A11"
36 = "A12"
37 = "A13"
38 = "A14"
39 = "A15"
40 = "VCC"
