# TMS7000 DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS7000"
title = "TMS7000/TMS7001"
dip = 40
width = 600
 1 = "B5, R/#W"
 2 = "B7, CLKOUT"
 3 = "B0"
 4 = "B1"
 5 = "B2"
 6 = "A0"
 7 = "A1"
 8 = "A2"
 9 = "A3"
10 = "A4"
11 = "A7"
12 = "#INT3"
13 = "#INT1"
14 = "#RESET"
15 = "A6, SCLK"
16 = "A5, RXD"
17 = "XTAL2, CLKIN"
18 = "XTAL1"
19 = "D7, A15"
20 = "D6, A14"
21 = "D5, A13"
22 = "D4, A12"
23 = "D3, A11"
24 = "D2, A10"
25 = "VCC"
26 = "D1, A9"
27 = "D0, A8"
28 = "C0, AD0"
29 = "C1, AD1"
30 = "C2, AD2"
31 = "C3, AD3"
32 = "C4, AD4"
33 = "C5, AD5"
34 = "C6, AD6"
35 = "C7, AD7"
36 = "MC, VCC"
37 = "B3, TXD"
38 = "B4, ALATCH"
39 = "B6, #ENABLE"
40 = "VSS"
