# TMS99105A DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS99105A"
dip = 40
width = 600
 1 = "#WE, #IOCLK"
 2 = "#RD"
 3 = "#RESET"
 4 = "#APP"
 5 = "#HOLD"
 6 = "VSS"
 7 = "READY"
 8 = "#INTREQ"
 9 = "#NMI"
10 = "IC0"
11 = "IC1"
12 = "IC2"
13 = "IC3"
14 = "R/#W"
15 = "VCC"
16 = "AD0/IN"
17 = "AD1"
18 = "AD2"
19 = "AD3"
20 = "AD4"
21 = "AD5"
22 = "AD6"
23 = "AD7"
24 = "AD8"
25 = "AD9"
26 = "AD10"
27 = "AD11"
28 = "AD12"
29 = "AD13"
30 = "AD14"
31 = "D15/OUT, #PSEL"
32 = "ALATCH"
33 = "VSS"
34 = "CLKOUT"
35 = ",      XTAL2"
36 = "CLKIN, XTAL1"
37 = "BST3"
38 = "BST2"
39 = "BST1"
40 = "#MEM"
