# TMS99105A DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS99105A"
dip = 40
width = 600
1 = "#WE, #IOCLK"
2 = "#RD"
3 = "#RESET"
4 = "#APP"
5 = "#HOLD"
6 = "VSS"
7 = "READY"
8 = "#INTREQ"
9 = "#NMI"
10 = "IC0"
11 = "IC1"
12 = "IC2"
13 = "IC3"
14 = "R/W"
15 = "VCC"
16 = "D0, A0, IN"
17 = "D1, A1"
18 = "D2, A2"
19 = "D3, A3"
20 = "D4, A4"
21 = "D5, A5"
22 = "D6, A6"
23 = "D7, A7"
24 = "D8, A8"
25 = "D9, A9"
26 = "D10, A10"
27 = "D11, A11"
28 = "D12, A12"
29 = "D13, A13"
30 = "D14, A14"
31 = "D15, OUT, #PSEL"
32 = "ALATCH"
33 = "VSS"
34 = "CLKOUT"
35 = "XTAL2"
36 = "XTAL1, CLKIN"
37 = "BST3"
38 = "BST2"
39 = "BST1"
40 = "#MEM"
