# µPD70116 DIP definition
# https://github.com/tgtakaoka/dip
name = "uPD70116"
title = uPD70116/V30
dip = 40
width = 600
 1 = "GND, IC"
 2 = "AD14"
 3 = "AD13"
 4 = "AD12"
 5 = "AD11"
 6 = "AD10"
 7 = "AD9"
 8 = "AD8"
 9 = "AD7"
10 = "AD6"
11 = "AD5"
12 = "AD4"
13 = "AD3"
14 = "AD2"
15 = "AD1"
16 = "AD0"
17 = "NMI"
18 = "INT"
19 = "CLK"
20 = "GND"
21 = "RESET"
22 = "READY"
23 = "#POLL"
24 = "#INTAK, QS1"
25 = "ASTB,   QS0"
26 = "#BUFEN, BS0"
27 = "BUF #R/W, BS1"
28 = "#IO/M, BS2"
29 = "#WR,   #BUSLOCK"
30 = "HLDAK,  #RQ/AK1"
31 = "HLDRQ,  #RQ/AK0"
32 = "#RD"
33 = "S/#LG"
34 = "#UBE"
35 = "A19, PS3"
36 = "A18, PS2"
37 = "A17, PS1"
38 = "A16, PS0"
39 = "AD15"
40 = "VDD"
