# W65C02S DIP definition
# https://github.com/tgtakaoka/dip
name = "W65C02S"
dip = 40
width = 600
1 = "#VP"
2 = "RDY"
3 = "PHI1O"
4 = "#IRQ"
5 = "#ML"
6 = "#NMI"
7 = "SYNC"
8 = "VDD"
9 = "A0"
10 = "A1"
11 = "A2"
12 = "A3"
13 = "A4"
14 = "A5"
15 = "A6"
16 = "A7"
17 = "A8"
18 = "A9"
19 = "A10"
20 = "A11"
21 = "VSS"
22 = "A12"
23 = "A13"
24 = "A14"
25 = "A15"
26 = "D7"
27 = "D6"
28 = "D5"
29 = "D4"
30 = "D3"
31 = "D2"
32 = "D1"
33 = "D0"
34 = "R/W"
35 = "NC"
36 = "BE"
37 = "PHI2"
38 = "#SO"
39 = "PHI2O"
40 = "#RES"
