# INS8060 DIP definition
# https://github.com/tgtakaoka/dip
name = "INS8060"
title = "INS8060(SC/MP II)"
dip = 40
width = 600
 1 = "P41, #WDS"
 2 = "P50, #RDS"
 3 = "P54, #ENIN"
 4 = "P55, #ENOUT"
 5 = "P47, #BREQ"
 6 = "P52, #HOLD"
 7 = "P53, #RST"
 8 = "P40, CONT"
 9 = "P10, DB7, H"
10 = "P11, DB6, D"
11 = "P12, DB5, I"
12 = "P13, DB4, R"
13 = "P14, DB3, AD15"
14 = "P15, DB2, AD14"
15 = "P16, DB1, AD13"
16 = "P17, DB0, AD12"
17 = "P42, SENSEA"
18 = "P43, SENSEB"
19 = "P34, FLAG0"
20 = "GND"
21 = "P35, FLAG1"
22 = "P36, FLAG2"
23 = "P44, SOUT"
24 = "P45, SIN"
25 = "P20, AD00"
26 = "P21, AD01"
27 = "P22, AD02"
28 = "P23, AD03"
29 = "P24, AD04"
30 = "P25, AD05"
31 = "P26, AD06"
32 = "P27, AD07"
33 = "P30, AD08"
34 = "P31, AD09"
35 = "P32, AD10"
36 = "P33, AD11"
37 = "P46, XIN"
38 = ", XOUT"
39 = "P40, #ADS"
40 = "VCC"
