# CDP1802 DIP definition
# https://github.com/tgtakaoka/dip
name = "CDP1802"
title = "CDP1802/CDP1806"
dip = 40
width = 600
 1 = "P46, CLOCK"
 2 = "P52, #WAIT"
 3 = "P53, #CLEAR"
 4 = "P33, Q"
 5 = "P45, SC1"
 6 = "P44, SC0"
 7 = "P50, #MRD"
 8 = "P17, BUS7"
 9 = "P16, BUS6"
10 = "P15, BUS5"
11 = "P14, BUS4"
12 = "P13, BUS3"
13 = "P12, BUS2"
14 = "P11, BUS1"
15 = "P10, BUS0"
16 = "VCC"
17 = "P32, N2"
18 = "P31, N1"
19 = "P30, N0"
20 = "VSS"
21 = "P37, #EF4"
22 = "P36, #EF3"
23 = "P35, #EF2"
24 = "P32, #EF1"
25 = "P20, MA0"
26 = "P21, MA1"
27 = "P22, MA2"
28 = "P23, MA3"
29 = "P24, MA4"
30 = "P25, MA5"
31 = "P26, MA6"
32 = "P27, MA7"
33 = "P41, TPB"
34 = "P40, TPA"
35 = "P51, #MWR"
36 = "P42, #INT"
37 = "P55, #DMAOUT"
38 = "P54, #DMAIN"
39 = ", #XTAL"
40 = "VDD"
