# MC68HC11D0 DIP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC11D0"
title = "MC68HC11D0 Mode3"
dip = 40
width = 600
 1 = "VSS"
 2 = "P10, AD0"
 3 = "P11, AD1"
 4 = "P12, AD2"
 5 = "P13, AD3"
 6 = "P14, AD4"
 7 = "P15, AD5"
 8 = "P16, AD6"
 9 = "P17, AD7"
10 = "P43, #XIRQ"
11 = "P41, R/W"
12 = "P40, AS"
13 = "P53, #RESET"
14 = "P42, #IRQ"
15 = "P45, RxD"
16 = "P44, TxD"
17 = ", MISO"
18 = ", MOSI"
19 = ", SCK"
20 = ", #SS"
21 = "VDD"
22 = ", PA7"
23 = ", PA5"
24 = ", PA3"
25 = ", PA2"
26 = ", PA1"
27 = ", PA0"
28 = "P27, A15"
29 = "P26, A14"
30 = "P25, A13"
31 = "P24, A12"
32 = "P23, A11"
33 = "P22, A10"
34 = "P21, A9"
35 = "P20, A8"
36 = "P51, MODB"
37 = "P50, MODA, #LIR"
38 = "P47, E"
39 = "P46, EXTAL"
40 = ", XTAL"
