# P8051AH DIP definition
# https://github.com/tgtakaoka/dip
name = "P8051"
title = "P8051AH"
dip = 40
width = 600
 1 = ", T2,   P1.0"
 2 = ", T2EX, P1.1"
 3 = ",     , P1.2"
 4 = ",     , P1.3"
 5 = ",     , P1.4"
 6 = ",     , P1.5"
 7 = ",     , P1.6"
 8 = ",     , P1.7"
 9 = "P53, RESET"
10 = "P45, RxD,   P3.0"
11 = "P44, TxD,   P3.1"
12 = "P43, #INT0, P3.2"
13 = "P42, #INT1, P3.3"
14 = ",    T0,    P3.4"
15 = ",    T1,    P3.5"
16 = "P51, #WR,   P3.6"
17 = "P50, #RD,   P3.7"
18 = ",    XTAL2"
19 = "P46, XTAL1"
20 = "VSS"
21 = "P20, A8,  P2.0"
22 = "P21, A9,  P2.1"
23 = "P22, A10, P2.2"
24 = "P23, A11, P2.3"
25 = "P24, A12, P2.4"
26 = "P25, A13, P2.5"
27 = "P26, A14, P2.6"
28 = "P27, A15, P2.7"
29 = "P41, #PSEN"
30 = "P40, ALE, #PROG"
31 = "GND, #EA, Vpp"
32 = "P17, AD7, P0.7"
33 = "P16, AD6, P0.6"
34 = "P15, AD5, P0.5"
35 = "P14, AD4, P0.4"
36 = "P13, AD3, P0.3"
37 = "P12, AD2, P0.2"
38 = "P11, AD1, P0.1"
39 = "P10, AD0, P0.0"
40 = "VCC"
