# SCN2650A DIP definition
# https://github.com/tgtakaoka/dip
name = "SCN2650A"
dip = 40
width = 600
 1 = "P45, SENSE"
 2 = "P34, ADR12"
 3 = "P33, ADR11"
 4 = "P32, ADR10"
 5 = "P31, ADR9"
 6 = "P30, ADR8"
 7 = "P27, ADR7"
 8 = "P26, ADR6"
 9 = "P25, ADR5"
10 = "P24, ADR4"
11 = "P23, ADR3"
12 = "P22, ADR2"
13 = "P21, ADR1"
14 = "P20, ADR0"
15 = "P54, #ADREN"
16 = "P53, RESET"
17 = "P42, #INTRQ"
18 = "P36, ADR14"
19 = "P35, ADR13"
20 = "P37, M/#IO"
21 = ", GND"
22 = "P51, WRP"
23 = "P41, #R/W"
24 = "P50, OPREQ"
25 = "P52, #DBUSEN"
26 = "P17, DBUS7"
27 = "P16, DBUS6"
28 = "P15, DBUS5"
29 = "P14, DBUS4"
30 = "P13, DBUS3"
31 = "P12, DBUS2"
32 = "P11, DBUS1"
33 = "P10, DBUS0"
34 = "P43, INTACK"
35 = "P47, RUN/#WAIT"
36 = "P55, #OPACK"
37 = "P40, #PAUSE"
38 = "P46, CLOCK"
39 = ", VCC"
40 = "P44, FLAG"
