# NS32016N DIP definition
# https://github.com/tgtakaoka/dip
name = "NS32016N"
dip = 48
width = 600
 1 = "AH6, A22"
 2 = "AH5, A21"
 3 = "AH4, A20"
 4 = "AH3, A19"
 5 = "AH2, A18"
 6 = "AH1, A17"
 7 = "AH0, A16"
 8 = "P27, AD15"
 9 = "P26, AD14"
10 = "P25, AD13"
11 = "P24, AD12"
12 = "P23, AD11"
13 = "P22, AD10"
14 = "P21, AD9"
15 = "P20, AD8"
16 = "P17, AD7"
17 = "P16, AD6"
18 = "P15, AD5"
19 = "P14, AD4"
20 = "P13, AD3"
21 = "P12, AD2"
22 = "P11, AD1"
23 = "P10, AD0"
24 = "GND, GNDL"
25 = "GND, GNDB"
26 = "P46, PHI1"
27 = "P47, PHI2"
28 = "P52, RDY"
29 = "Cap, BBG"
30 = "P41, #HOLD"
31 = "P45, #HLDA"
32 = "ST7, #HBE"
33 = "P50, #DS,  #FLT"
34 = "P53, #RST, #ABT"
35 = "P44, #AT,  #SPC"
36 = "ST4, U/#S"
37 = "P40, #ADS"
38 = "ST6, #DDIN"
39 = "P51, #PFS"
40 = "ST3, ST3"
41 = "ST2, ST2"
42 = "ST1, ST1"
43 = "ST0, ST0"
44 = "ST5, #ILO"
45 = "P43, #NMI"
46 = "P42, #INT"
47 = "AH7, A23"
48 = "VCC, VCC"
