# P80C88 DIP definition
# https://github.com/tgtakaoka/dip
name = "P80C88A"
dip = 40
width = 600
 1 = "GND"
 2 = "P26, A14"
 3 = "P25, A13"
 4 = "P24, A12"
 5 = "P23, A11"
 6 = "P22, A10"
 7 = "P21, A9"
 8 = "P20, A8"
 9 = "P17, AD7"
10 = "P16, AD6"
11 = "P15, AD5"
12 = "P14, AD4"
13 = "P13, AD3"
14 = "P12, AD2"
15 = "P11, AD1"
16 = "P10, AD0"
17 = "P43, NMI"
18 = "P42, INTR"
19 = "P46, CLK"
20 = "GND"
21 = "P53, RESET"
22 = "P52, READY"
23 = ",    #TEST"
24 = "P54, #INTA, QS1"
25 = "P40, ALE,   QS0"
26 = "P44, #DEN,  #S0"
27 = "P35, DT/#R, #S1"
28 = "P55, IO/#M, #S2"
29 = "P51, #WR,   #LOCK"
30 = "P36, HLDA,  #RQ/GT1"
31 = "P37, HOLD,  #RQ/GT0"
32 = "P50, #RD"
33 = "P47, MN/#MX"
34 = "P34, #SS0"
35 = "P33, A19,   S6"
36 = "P32, A18,   S5"
37 = "P31, A17,   S4"
38 = "P30, A16,   S3"
39 = "P27, A15"
40 = "VCC"
