# Z8001 DIP definition
# https://github.com/tgtakaoka/dip
name = "Z16C01"
title = "Z08001/Z16C01 (Z8001)"
dip = 48
width = 600
 1 = "P10, AD0"
 2 = "P21, AD9"
 3 = "P22, AD10"
 4 = "P23, AD11"
 5 = "P24, AD12"
 6 = "P25, AD13"
 7 = "P51, #STOP"
 8 = "   , #MI"
 9 = "P27, AD15"
10 = "P26, AD14"
11 = "VCC"
12 = "P44, #VI"
13 = "P42, #NVI"
14 = "P50, #SEGT"
15 = "P43, #NMI"
16 = "P53, #RESET"
17 = "   , #MO"
18 = "P47, #MREQ"
19 = "P45, #DS"
20 = "ST3, ST3"
21 = "ST2, ST2"
22 = "ST1, ST1"
23 = "ST0, ST0"
24 = "SN3, SN3"
25 = "SN1, SN1"
26 = "SN0, SN0"
27 = "P37, #BUSREQ"
28 = "P52, #WAIT"
29 = "P36, #BUSACK"
30 = "P41, R/#W"
31 = "ST4, N/#S"
32 = "ST5, B/#W"
33 = "   , NC"
34 = "P40, #AS"
35 = "P46, CLOCK"
36 = "GND"
37 = "SN2, SN2"
38 = "P11, AD1"
39 = "P12, AD2"
40 = "P13, AD3"
41 = "P15, AD5"
42 = "SN4, SN4"
43 = "P14, AD4"
44 = "P16, AD6"
45 = "P17, AD7"
46 = "SN5, SN5"
47 = "SN6, SN6"
48 = "P16, AD6"
