# Z8002 DIP definition
# https://github.com/tgtakaoka/dip
name = "Z8002"
title = "Z8002"
dip = 40
width = 600
 1 = "P21, AD9"
 2 = "P22, AD10"
 3 = "P23, AD11"
 4 = "P24, AD12"
 5 = "P25, AD13"
 6 = "P51, #STOP"
 7 = "P55, #MI"
 8 = "P27, AD15"
 9 = "P26, AD14"
10 = "VCC"
11 = "P44, #VI"
12 = "P43, #NVI"
13 = "P42, #NMI"
14 = "P53, #RESET"
15 = "P54, #MO"
16 = "P47, #MREQ"
17 = "P45, #DS"
18 = "P33, ST3"
19 = "P32, ST2"
20 = "P31, ST1"
21 = "P30, ST0"
22 = "P37, #BUSREQ"
23 = "P52, #WAIT"
24 = "P36, #BUSACK"
25 = "P41, R/#W"
26 = "P34, N/#S"
27 = "P35, B/#W"
28 = ",    NC"
29 = "P40, #AS"
30 = "P46, CLOCK"
31 = "GND"
32 = "P11, AD1"
33 = "P12, AD2"
34 = "P13, AD3"
35 = "P14, AD5"
36 = "P15, AD4"
37 = "P16, AD6"
38 = "P17, AD7"
39 = "P20, AD8"
40 = "P10, AD0"
