# TMS7001 DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS7001"
title = "TMS7001"
dip = 40
width = 600
 1 = "P41, R/#W,   B5"
 2 = "P55, CLKOUT, B7"
 3 = "P50,       , B0"
 4 = "P51,       , B1"
 5 = "P52,       , B2"
 6 = "P30,       , A0"
 7 = "P31,       , A1"
 8 = "P32,       , A2"
 9 = "P33,       , A3"
10 = "P34,       , A4"
11 = "P37,       , A7"
12 = "P42, #INT3"
13 = "P43, #INT1"
14 = "P53, #RESET"
15 = "P36, SCLK,  A6"
16 = "P35, RXD,   A5"
17 = "P46, CLKIN, XTAL2"
18 = "   ,      , XTAL1"
19 = "P27, A15, D7"
20 = "P26, A14, D6"
21 = "P25, A13, D5"
22 = "P24, A12, D4"
23 = "P23, A11, D3"
24 = "P22, A10, D2"
25 = "VCC"
26 = "P21, A9,  D1"
27 = "P20, A8,  D0"
28 = "P10, AD0, C0"
29 = "P11, AD1, C1"
30 = "P12, AD2, C2"
31 = "P13, AD3, C3"
32 = "P14, AD4, C4"
33 = "P15, AD5, C5"
34 = "P16, AD6, C6"
35 = "P17, AD7, C7"
36 = "VCC,    , MC"
37 = "P44, TXD, B3"
38 = "P40, ALATCH, B4"
39 = "P47, #ENABLE, B6"
40 = "VSS"
