# P8048AH DIP definition
# https://github.com/tgtakaoka/dip
name = "P8048"
title = "P8048AH"
dip = 40
width = 600
 1 = "P44, T0"
 2 = "P46, XTAL1"
 3 = ",    XTAL2"
 4 = "P53, #RESET"
 5 = "P52, #SS"
 6 = "P42, #INT"
 7 = "VCC, EA"
 8 = "P50, #RD"
 9 = "P41, #PSEN"
10 = "P51, #WR"
11 = "P40, ALE"
12 = "P10, DB0"
13 = "P11, DB1"
14 = "P12, DB2"
15 = "P13, DB3"
16 = "P14, DB4"
17 = "P15, DB5"
18 = "P16, DB6"
19 = "P17, DB7"
20 = "GND, VSS"
21 = "P20, A8"
22 = "P21, A9"
23 = "P22, A10"
24 = "P23, A11"
25 = "P55, #PROG"
26 = "VCC, VDD"
27 = ", P10"
28 = ", P11"
29 = ", P12"
30 = ", P13"
31 = ", P14"
32 = ", P15"
33 = ", P16"
34 = ", P17"
35 = ", P24"
36 = ", P25"
37 = ", P26"
38 = ", P27"
39 = "P45, T1"
40 = "VCC"
