# IM6100 DIP definition
# https://github.com/tgtakaoka/dip
name = "IM6100"
title = "IM6100"
dip = 40
width = 600
 1 = "VCC"
 2 = "P45, RUN"
 3 = "P36, DMAGNT"
 4 = "P37, #DMAREQ"
 5 = "P42, #CPREQ"
 6 = "P41, #RUN/HLT"
 7 = "P53, #RESET"
 8 = "P43, #INTREQ"
 9 = "P30, XTA"
10 = "P40, LXMAR"
11 = "P52, #WAIT"
12 = "P31, XTB"
13 = "P32, XTC"
14 = "P46, OSC OUT"
15 = "GND, OSC IN"
16 = "P23, DX0"
17 = "P22, DX1"
18 = "P21, DX2"
19 = "P20, DX3"
20 = "P17, DX4"
21 = "P16, DX5"
22 = "P15, DX6"
23 = "P14, DX7"
24 = "P13, DX8"
25 = "P12, DX9"
26 = ", GND"
27 = "P11, DX10"
28 = "P10, DX11"
29 = "P44, LINK"
30 = "P47, #DEVSEL"
31 = "P34, #SWSEL"
32 = "P26, #C0"
33 = "P25, #C1"
34 = "P24, #C2"
35 = "P27, #SKP"
36 = "P51, IFETCH"
37 = "P55, #MEMSEL"
38 = "P35, #CPSEL"
39 = "P54, INTGNT"
40 = "P50, DATAF"
