# TMS9995 DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS9995"
dip = 40
width = 600
 1 = ",    XTAL1"
 2 = "P46, CLKIN, XTAL2"
 3 = "P47, CLKOUT"
 4 = "P10, D7"
 5 = "P11, D6"
 6 = "P12, D5"
 7 = "P13, D4"
 8 = "P14, D3"
 9 = "P15, D2"
10 = "VCC"
11 = "P16, D1"
12 = "P17, D0"
13 = "P45, CRUIN"
14 = "P44, #INT4, #EC"
15 = "P42, #INT1"
16 = "P55, IQA, HOLDA"
17 = "P50, #DBIN"
18 = "P40, #HOLD"
19 = "P51, #WE, #CRUCLK"
20 = "P54, #MEMEN"
21 = "P43, #NMI"
22 = "P53, #RESET"
23 = "P52, READY"
24 = "P37, A0"
25 = "P36, A1"
26 = "P35, A2"
27 = "P34, A3"
28 = "P33, A4"
29 = "P32, A5"
30 = "P31, A6"
31 = "GND"
32 = "P30, A7"
33 = "P27, A8"
34 = "P26, A9"
35 = "P25, A10"
36 = "P24, A11"
37 = "P23, A12"
38 = "P22, A13"
39 = "P21, A14"
40 = "P20, A15, CRUOUT"
