# TMS99105A DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS99105A"
dip = 40
width = 600
 1 = "P51, #WE, #IOCLK"
 2 = "P50, #RD"
 3 = "P53, #RESET"
 4 = "P36, #APP"
 5 = "P37, #HOLD"
 6 = "VSS"
 7 = "P52, READY"
 8 = "P42, #INTREQ"
 9 = "P43, #NMI"
10 = "P37, IC0"
11 = "P36, IC1"
12 = "P35, IC2"
13 = "P34, IC3"
14 = "P45, R/#W"
15 = "VCC"
16 = "P27, AD0/IN"
17 = "P26, AD1"
18 = "P25, AD2"
19 = "P24, AD3"
20 = "P23, AD4"
21 = "P22, AD5"
22 = "P21, AD6"
23 = "P20, AD7"
24 = "P17, AD8"
25 = "P16, AD9"
26 = "P15, AD10"
27 = "P14, AD11"
28 = "P13, AD12"
29 = "P12, AD13"
30 = "P11, AD14"
31 = "P10, D15/OUT, #PSEL"
32 = "P44, ALATCH"
33 = "VSS"
34 = "P47, CLKOUT"
35 = "   , XTAL2"
36 = "P46, CLKIN, XTAL1"
37 = "P30, BST3"
38 = "P31, BST2"
39 = "P32, BST1"
40 = "P54, #MEM"
